<!-- // Begin Module: Standard Content \\ -->
<table border="0" cellpadding="20" cellspacing="0" width="100%">
   <tr>
      <td valign="top">
         <div mc:edit="std_content00">
            <h4 class="h4">Hey $sellername$,</h4>
            This is just a friendly reminder that you have the following offer pending from $buyername$ on the ad &quot;$adtitle$&quot; .
            <br />
            <br />
			Offer: <strong>$offer$</strong>
			<br />
            $buyername$'s Reputation: <strong>$buyer_rep$</strong>
            <br />
            <br />
             Don't leave 'em hangin'! Click the link below to let them know whether or not you want to continue with the exchange.                                                       
         	</div>		
         			 																							 
		   <div mc:edit="std_social">
		   <br />                                                           		
				<a style="color:#006dcc;" href="$server_url$/$viewing_url$">$adtitle$</a> 	
            <br />            
         </div>
         Thank you for using our service, and good luck in your wheelings and dealings.
            <br />
            <br />
            - The Team at Kagu Buzz
      </td>
   </tr>
</table>
<!-- // End Module: Standard Content \\ -->
					