<table border="0" cellpadding="20" cellspacing="0" width="100%">
    <tr>
        <td valign="top">        
            <div mc:edit="std_content00">
            <h4 class="h4">Hey $recipient_name$,</h4>
                <br/>
                Your $post_type$ posting "$post_title$" ending on $end_date$ is about to expire. 
                <br/>
                <br/>
                $post_summary$                                                      
                <br/>
                <br/>
                <div mc:edit="std_social">
                	<a style="color:#006dcc;" href="$server_url$/$viewing_url$">Follow this link to View your post.</a> 
                <br />
                <br />
                OR
                <br />
                <br />
                    <a style="color:#006dcc;" href="$server_url$/events/manage/autorenew?id=$post_id$">Follow this link to Renew your post for another 30 days.</a> 
                </div>
                <div mc:edit="std_content00">
                <br />
                Thank you for using our service,
                <br />
                <br />
                The Team at Kagu Buzz
            </div>            
        </td>
    </tr>
</table>