<table border="0" cellpadding="20" cellspacing="0" width="100%">
    <tr>
        <td valign="top">        
            <div mc:edit="std_content00">
                <h4 class="h4">Hey $recipient_name$!</h4>
                <br/> 
                <br/>
                Just FYI, $post_owner$ has started a new discussion about your event called "$post_title$".
                <br/> 
                <br/>
                $post_summary$                                                     
                <br/>
                <br/>
                You can view the discussion here:
                <br/>
                <br/>
                <div mc:edit="std_social">
                    <a style="color:#006dcc;" href="$server_url$/$viewing_url$">$post_title$</a> 
                    <br>
                    <br>
                    <a style="color:#da4f49;" href="$server_url$/discussion/public/unsubscribe/$post_id$">Unsubscribe Me From this Discussion</a>
                </div>
                <div mc:edit="std_content00">
                <br />
                Thank you for using our service,
                <br />
                The Team at Kagu Buzz
            </div>														                                                    	
    	</td>
    </tr>
</table>