<table border="0" cellpadding="20" cellspacing="0" width="100%">
    <tr>
        <td valign="top">        
            <div mc:edit="std_content00">
            <h4 class="h4">Hey $recipient_name$,</h4>
                <br/>
                $sender$ just posted a new question for your ad <a style="color:#006dcc;" href="$server_url$/$viewing_url$">$ad_title$</a>.
                <br/> 
                <br/>
                "$post_summary$"                                                     
                <br/>
                <br/>
                <div mc:edit="std_content00">
                <br />
                Thank you for using our service,
                <br />
                <br />
                The Team at Kagu Buzz
            </div>            
        </td>
    </tr>
</table>