<table border="0" cellpadding="20" cellspacing="0" width="100%">
    <tr>
        <td valign="top">        
            <div mc:edit="std_content00">
                <h4 class="h4">Hello $recipient_name$,</h4>
                <br/> 
                <br/>
                You have a new private message from $sender_name$ regarding "$message_title$":
                <br/> 
                <br/>
                $message$                                                     
                <br/>
                To respond, please follow this link:
                <br/>
                <br/>
                <div mc:edit="std_social">
                    <a style="color:#006dcc;" href="$server_url$/$viewing_url$">$message_title$</a> 
                </div>
                <div mc:edit="std_content00">
                <br />
                Thank you for using our service,
                <br />
                The Team at Kagu Buzz
            </div>														                                                    	
    	</td>
    </tr>
</table>
    