<table border="0" cellpadding="20" cellspacing="0" width="100%">
    <tr>
        <td valign="top">        
            <div mc:edit="std_content00">
                <h4 class="h4">Hey $recipient_name$,</h4>
                Welcome to Kagu Buzz, the social networking site that makes it easier to connect with others and enjoy your local community.  
                <br/>
                <br/> 
                We are continually trying to make your experience here better and would love your ideas, suggestions, and concerns. Please submit ideas or feedback by clicking on the 'feedback' tab on the right side of any page.
           </div>                                                                                                                    
           <div mc:edit="std_content00">
       			<br/>
                Thank you again and welcome to Kagu Buzz!
                <br/>
                <br/>
                - The Team at Kagu Buzz
            </div>														                                                    	
    	</td>
    </tr>
</table>
    