<table border="0" cellpadding="20" cellspacing="0" width="100%">
    <tr>
        <td valign="top">        
            <div mc:edit="std_content00">
            <h4 class="h4">Hey $recipient_name$,</h4>
                <br/>
                $post_owner$ just posted a new $post_type$ called "$post_title$".
                <br/> 
                <br/>
                $post_summary$                                                      
                <br/>
                <br/>
                Check out the new post here:
                <br/>
                <br/>
                <div mc:edit="std_social">
                    <a style="color:#006dcc;" href="$server_url$/$viewing_url$">$post_title$</a> 
                </div>
                <div mc:edit="std_content00">
                <br />
                Thank you for using our service,
                <br />
                <br />
                The Team at Kagu Buzz
                </div>
            </div>            
        </td>
    </tr>
</table>