<table border="0" cellpadding="20" cellspacing="0" width="100%">
    <tr>
        <td valign="top">        
            <div mc:edit="std_content00">
                <h4 class="h4">Hey $recipient_name$,</h4>
                <br />
                <br />
                This email is just to let you know that your Kagu Buzz password has been changed.<br><br>
                 
                Important account security tips:<br><br>
- Never give out your password or personal information by email or on social
 networks. Kagu Buzz will never contact you to ask you for your password.<br><br>
- Never use the same password for Kagu Buzz and other websites.<br><br>
                                                         
             </div>
                                                                                                                                                                                                         
            <div mc:edit="std_content00">
                <br />
                Thank you for using our service,
                <br />
                <br />
                The Team at Kagu Buzz
            </div>            
        </td>
    </tr>
</table>