<!-- // Begin Module: Standard Content \\ -->
<table border="0" cellpadding="20" cellspacing="0" width="100%">
   <tr>
      <td valign="top">
         <div mc:edit="std_content00">
            <h4 class="h4">Hey $buyername$,</h4>
            Your offer on the ad &quot;$adtitle$&quot; has been sent to $sellername$.
            <br />
            <br />
            Offer: <strong>$offer$</strong>
            <br />
            <br />
            $sellername$ now has the option of thinking about, declining, or accepting your offer and should be back in contact with you shortly.                                                                                                                                                                                                                                                 		
            <br/>
            <br/>
            Thank you for using our service, and good luck in your wheelings and dealings!
            <br />
            <br />
            - The Team at Kagu Buzz
         </div>
      </td>
   </tr>
</table>
<!-- // End Module: Standard Content \\ -->