<!-- // Begin Module: Standard Content \\ -->
<table border="0" cellpadding="20" cellspacing="0" width="100%">
   <tr>
      <td valign="top">
         <div mc:edit="std_content00">
            <h4 class="h4">Hey $sellername$,</h4>
            You offered to think on the offer from $buyername$ for the ad &quot;$adtitle$&quot; .
            <br />
            <br />
			Offer: <strong>$offer$</strong>
			<br />
            $buyername$'s Reputation: <strong>$buyer_rep$</strong>
            <br />
            <br />
            $buyername$ is free to make another offer if the item is still available, but per Kagu Buzz etiquette, you should contact $buyername$ with a decision within 3 days.                                                       
         </div>
         <div mc:edit="std_content00">
            <br>  
            Don't leave 'em hangin'!
            <br />
            Thank you for using our service, and good luck in your wheelings and dealings.
            <br />
            <br />
            - The Team at Kagu Buzz
         </div>
      </td>
   </tr>
</table>
<!-- // End Module: Standard Content \\ -->