<table border="0" cellpadding="20" cellspacing="0" width="100%">
    <tr>
        <td valign="top">        
            <div mc:edit="std_content00">
            <h4 class="h4">Hey $recipient_name$,</h4>
                <br/>
                We wanted to remind you that the $post_type$ you bookmarked called "$post_title$" is happening tomorrow.
                <br/> 
                <br/>
                $post_summary$                                                      
                <br/>
                <br/>
                Need to jog your memory? Check out the $post_type$ here:   
                <br/>
                <br/>
                <div mc:edit="std_social">
                    <a style="color:#006dcc;" href="$server_url$/$viewing_url$">$post_title$</a> 
                </div>
                <div mc:edit="std_content00">
                <br />
                Thank you for using our service,
                <br />
                <br />
                The Team at Kagu Buzz
            </div>            
        </td>
    </tr>
</table>