<!-- // Begin Module: Standard Content \\ -->
<table border="0" cellpadding="20" cellspacing="0" width="100%">
   <tr>
      <td valign="top">
         <div mc:edit="std_content00">
            <h4 class="h4">Hey $recipient$,</h4>
            The exchange with $other_party$ &quot;$adtitle$&quot; was marked as Accepted a couple of weeks ago.  Have you exchanged the goods or services yet?  If so let others benefit from your experience with $other_party$. Share the love and click the link below to rate your experience with them.                                                      
         	</div>		
         			 																							 
		   <div mc:edit="std_social">
		   <br />                                                           		
				<a style="color:#006dcc;" href="$server_url$/$viewing_url$">$adtitle$</a> 	
            <br />            
         </div>
         Thank you for using our service, and good luck in your wheelings and dealings.
            <br />
            <br />
            - The Team at Kagu Buzz
      </td>
   </tr>
</table>
<!-- // End Module: Standard Content \\ -->
					