<table border="0" cellpadding="20" cellspacing="0" width="100%">
    <tr>
        <td valign="top">        
            <div mc:edit="std_content00">
            <h4 class="h4">Hey $recipient_name$,</h4>
                <br/>
                $sender$ has answered your question for the ad "$ad_title$"
                <br/> 
                <br/>
                "$post_summary$"
                <br/>
                <br/>
                Need to jog your memory? Check out the ad here:   
                <br/>
                <br/>
                <div mc:edit="std_social">
                    <a style="color:#006dcc;" href="$server_url$/$viewing_url$">$ad_title$</a> 
                </div>
                <br />
                Thank you for using our service,
                <br />
                <br />
                The Team at Kagu Buzz
            </div>            
        </td>
    </tr>
</table>