<!-- // Begin Module: Standard Content \\ -->
<table border="0" cellpadding="20" cellspacing="0" width="100%">
	<tr>
		<td valign="top">
			<div mc:edit="std_content00">
				<h4 class="h4">Hey $sellername$,</h4>
				<strong>$buyername$ </strong> made an offer on your ad &quot;$adtitle$&quot;.
				<br />
				<br />
				Offer: <strong>$offer$</strong> 
				<br />
                $buyername$'s Reputation: <strong>$buyer_rep$</strong> 
				<br />
				<br />
				To keep your information private, this email was sent by Kagu Buzz on behalf of <strong>$buyername$</strong>.  
				Since you have already accepted another offer, you can only accept $buyername$'s new offer by canceling the currently accepted offer. Please log in to do so.                                                             
			 </div>																									 
			<div mc:edit="std_content00">
				<br />
				Thank you for using our service, and good luck in your wheelings and dealings.
				<br />
				<br />
				- The Team at Kagu Buzz
			</div>
		</td>
	</tr>
</table>
<!-- // End Module: Standard Content \\ -->

