<table border="0" cellpadding="20" cellspacing="0" width="100%">
    <tr>
        <td valign="top">        
            <div mc:edit="std_content00">
                <h4 class="h4">Hey $recipient_name$,</h4>
                <br />
                <br />
                You're almost finished!
             </div>
                                                                                                                 
           <div mc:edit="std_social">
                <br />
               <a style="color:#006dcc;" href="$server_url$/accountverify?id=$recipient_id$&securityCode=$recipient_security_code$">Please follow this link to verify that this is your email.</a> 
            </div>
                                                                                                                     
            <div mc:edit="std_content00">
                <br />
                Thank you for using our service,
                <br />
                <br />
                The Team at Kagu Buzz
            </div>            
        </td>
    </tr>
</table>