<!-- // Begin Module: Standard Content \\ -->
<table border="0" cellpadding="20" cellspacing="0" width="100%">
	<tr>
		<td valign="top">
			<div mc:edit="std_content00">
				<h4 class="h4">Hey $sellername$, we have some great news!</h4>
				<strong>$buyername$ </strong> made an offer on your ad &quot;$adtitle$&quot;.
				<br />
				<br />
				Offer: <strong>$offer$</strong>
				<br />
                $buyername$'s Reputation: <strong>$buyer_rep$</strong>
				<br />
				<br />
				To keep your information private, this email was sent by Kagu Buzz on behalf of <strong>$buyername$</strong>. You can automatically reply to the offer by selecting one of the options below:                                                             
			 </div>																									 
		   <div mc:edit="std_social">
		   <br />                                                           		
				<a style="color:#da4f49;" href="$server_url$/transaction/accept?id=$discussionid$&amp;adcode=$UUID$">I Accept!</a>
				&nbsp;&nbsp;&nbsp;<a style="color:#006dcc;" href="$server_url$/transaction/decline?id=$discussionid$&amp;adcode=$UUID$">No Thanks.</a> 
				&nbsp;&nbsp;&nbsp;<a style="color:#5bb75b;" href="$server_url$/transaction/think_on_it?id=$discussionid$&amp;adcode=$UUID$">Let Me Think On It</a>                                                                
				&nbsp;
			</div>
																													 
			<div mc:edit="std_content00">
				<br />
				Thank you for using our service, and good luck in your wheelings and dealings.
				<br />
				<br />
				- The Team at Kagu Buzz
			</div>
		</td>
	</tr>
</table>
<!-- // End Module: Standard Content \\ -->

