<!-- // Begin Module: Standard Content \\ -->
<table border="0" cellpadding="20" cellspacing="0" width="100%">
   <tr>
      <td valign="top">
         <div mc:edit="std_content00">
            <h4 class="h4">Hey $sellername$,</h4>
            You accepted <strong>$buyername$&rsquo;s</strong> offer on the ad &quot;$adtitle$&quot; from .
            <br />
            <br />
            Offer: <strong>$offer$</strong>
            <br />
            $buyername$'s Reputation: <strong>$buyer_rep$</strong
            <br />
            <br />
            To begin exchanging the goods, you can reach <strong>$buyername$</strong> via $buyercontactmethod$ at $buyercontactdetails$.                                                           
         </div>
         <div mc:edit="std_content00">
            <br />
            Thank you for using our service, and good luck in your wheelings and dealings.
            <br />
            <br />
            - The Team at Kagu Buzz
         </div>
      </td>
   </tr>
</table>
<!-- // End Module: Standard Content \\ -->