<table border="0" cellpadding="20" cellspacing="0" width="100%">
    <tr>
        <td valign="top">        
            <div mc:edit="std_content00">
                <h4 class="h4">Hey $recipient_name$!</h4>
                <br />
                Congrats! It looks like you made a good impression, $referenced_user$ just recommended you on Kagu Buzz. This recommendation increases your overall reputation and trustworthiness on Kagu Buzz.                                                      
             </div>
            <br />                                                                                                             
            <div mc:edit="std_content00">
                Thank you,
                <br />
                The Team at Kagu Buzz
            </div>            
        </td>
    </tr>
</table>