<!-- // Begin Module: Standard Content \\ -->
<table border="0" cellpadding="20" cellspacing="0" width="100%">
	<tr>
		<td valign="top">
			<div mc:edit="std_content00">
				<h4 class="h4">Hello $recipient$,</h4>
				This is a notice to let you know that the exchange for the ad &quot;$adtitle$&quot;, with $other_party$ has been closed.
				<br />
				<br />
				By now you should have made an exchange of goods or services with $other_party$. Please take a few moments to rate your exchange with $other_party$ here so that others can benefit from your experience:		
			 </div>				
			 <br />
				<a style="color:#006dcc;" href="$server_url$/$viewing_url$">$adtitle$</a> 																					 
			<div mc:edit="std_content00">
				<br />
				Thank you for using our service, and good luck in your wheelings and dealings!
				<br />
				<br />
				- The Team at Kagu Buzz
			</div>
		</td>
	</tr>
</table>
<!-- // End Module: Standard Content \\ -->

