<!-- // Begin Module: Standard Content \\ -->
<table border="0" cellpadding="20" cellspacing="0" width="100%">
   <tr>
      <td valign="top">
         <div mc:edit="std_content00">
            <h4 class="h4">Hey $buyername$,</h4>
            <strong>$sellername$</strong> declined your offer on the ad &quot;$adtitle$&quot;.
            <br />
            <br />
            Offer: <strong>$offer$</strong>
            <br />
            <br />
            Feel free to make another offer if the item is still available.                                                          
         </div>
         <div mc:edit="std_content00">
            <br />
            Thank you for using our service, and good luck in your wheelings and dealings.
            <br />
            <br />
            - The Team at Kagu Buzz
         </div>
      </td>
   </tr>
</table>
<!-- // End Module: Standard Content \\ -->
