Hello $recipient_name$!
<br>
<br>
 Welcome to Kagu Buzz, the social networking site where we try to make it a little easier to connect with others and enjoy your local community. We are continually trying to make 
 your experience here better and would love your ideas, suggestions, and concerns. Please submit any feedback you might have by clicking the 'feedback' tab on the right side of any page.
<br>
<br>
Thanks again and welcome,
<br>
The Team at Kagu Buzz