Hi $sellername$,
<br>
<br>
$buyername$ has submitted $new_offer$ offer on your ad "$adtitle$".
<br />
<br />
Offer: <strong>$offer$</strong>
<br>
<br>
You can automatically reply to the offer by selecting one of the options below.                                                            
<br>
<br>
<div style="text-align: right">
<a href="$server_url$/transaction/accept?id=$discussionid$&amp;adcode=$UUID$" class="btn btn-success">I Accept</a>
<a href="$server_url$/transaction/decline?id=$discussionid$&amp;adcode=$UUID$" class="btn btn-error">No Thanks</a>
<a href="$server_url$/transaction/think_on_it?id=$discussionid$&amp;adcode=$UUID$"class="btn btn-primary">Let Me Think On It</a>
</div>

