Hello $recipient$,
<br />
<br />
This is a notice to let you know that the exchange for the ad <strong>&quot;$adtitle$&quot;</strong> with $other_party$ has been canceled. If you feel this should not be the case, please contact $other_party$ by clicking on the reply button below. Otherwise, please take a few moments to rate your exchange so that others can benefit from your experience. Clicking on the 'Rate This Exchange With $other_party$' button at the top of this page to do so.
<br />
<br />



