Hey $recipient_name$!
<br>
<br>
$post_owner$ has contributed to the discussion $post_title$. We thought you might be interested since you are a participant in this discussion.
<br>
<br>
<div mc:edit="std_social">
<a style="color:#006dcc;" href="$server_url$/$viewing_url$">$post_title$</a> 
<br>
<br>
<a style="color:#da4f49;" href="$server_url$/discussion/public/unsubscribe/$post_id$">Unsubscribe Me From this Discussion</a>
</div>
<br>
<br>
Enjoy,
<br>
The Team at Kagu Buzz
