You offered to think on $buyername$'s  offer on your ad "$adtitle$". Don't leave 'em hangin'!
<br />
<br />
Offer: <strong>$offer$</strong>
<br>
<br>
Use the reply link to start a private conversation with $buyername$, or you can automatically decline or accept the offer using the buttons below.
<br>
<br>
<div style="text-align: right">
<a href="$server_url$/transaction/accept?id=$discussionid$&adcode=$UUID$" class="btn btn-success">I Accept</a>
<a href="$server_url$/transaction/decline?id=$discussionid$&adcode=$UUID$" class="btn btn-error">No Thanks</a>
</div>